### ISSUE TITLE
CRLF - windows and unix

### ISSUE THREAD

**Issue by d0nk0tr0n** [Xorlent/Stretchoid#1]
Hi, love this project, I was setting up to contribute as I got nmap scanned per IDS by what is probably stretchoid. I cloned and branched and then saw CRLF in the file. Can we clean those up in the repo? I have set my global git config per github recommendations for linux per: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows.

-Thanks!

**Comment by Xorlent** [comment]
Thanks, I use the API, not Git to push the file (from a Windows host) to the repo on a schedule.

What are you using to process the file and what issue do you run into as a result of the CRLF?  I'll see what I can do, but just want to first understand what issue it causes for you.  At the moment we consume this file as-is on firewall appliances, but I assume you are doing something else with the list.

**Comment by d0nk0tr0n** [comment]
I was going to try to contribute a patch and add an IP address to the list but as I run linux the CRLF is problematic.
At any, rate I was going to add 4.151.38.194 as they nmapped me per suricata after using the strechoid blocklist on my firewall. Which I didn't see in the most recent list in main branch.
Looks like an azure host - https://www.whois.com/whois/4.151.38.194

**Comment by Xorlent** [comment]
That is an interesting finding.  Let me do some research and get back to you.  Thanks for reporting the omission!

**Comment by Xorlent** [comment]
Thank you.  It's tricky trying to reliably harvest all of the PTR records, but I will keep you posted on my progress and let you know when I think we've made progress.

**Comment by Xorlent** [comment]
Okay, I'm trying a new approach.  The first run will take a long time to ensure the results are complete (a few months!), but I will update the list as new IPs are discovered.  

You may want to take a look at the [Canary Cloudflare](https://github.com/Xorlent/Canary-Cloudflare) repo, as the webhook functionality would allow you to block as soon as an unwanted scanner hits the honeypot.

**Comment by Xorlent** [comment]
Newly processed blocks are beginning to hit the IP list, FYI.  The file will continue to be updated every few days until it's a complete data set.

Thanks again for letting me know about the missing entries.
