### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by d0nk0tr0n** [Xorlent/Stretchoid#3]
Hi, just wanted to thank you. I see the stretchoid hosts have recently jumped from around ~1200 to ~1600 on my firewall alias from the recent update. Things have been quiet in the logs for me the last few days. Just wanted to share some positive feedback and appreciation.

**Comment by Xorlent** [comment]
I'm so glad it is working for you -- and thanks for the feedback.  It will still be a number of weeks before we get full coverage, at which point the scripts will continue to run in an effort to keep up with the latest IPs.
