### ISSUE TITLE
Missing IPs

### ISSUE THREAD

**Issue by RandelP** [Xorlent/Stretchoid#4]
Thank you for providing the list. I run a script that utilizes dig to query the following subdomains with a numerical suffix (0-100):

azpdcg
azpdcgb
azpdcgc
azpdcs
azpdcsb
azpdcsc
azpdeg
azpdegb
azpdegc
azpdes
azpdesb
azpdesc
azpdse
azpdsg
azpdsgb
azpdsgc
azpdss
azpdssb
azpdssc
azpdwg
azpdwgb
azpdwgc
azpdws
azpdwsb
azpdwsc

I have noticed several discrepancies between your list and my results. Could you please provide more details on how you generate and maintain your lists? This information would be helpful for reconciling the differences.

Attached are the results from my list.
[list.txt](https://github.com/user-attachments/files/16502103/list.txt)

Thank you!

**Comment by Xorlent** [comment]
Thanks for your note.

1. Some of the IPs in this repository's list are carry-overs from the former Stretched list, but I intend to purge them shortly.
2. The initial list generation is still in process, I suspect it will be a few more weeks before it's completed an exhaustive search.
3. I love your approach to locating the Stretchoid IPs!  May I recommend expanding your suffix to, say, 150 or so? :)
4. Your approach has identified some IPs I was not aware of, which is very helpful.  As far as I can tell, you've got all the prefixes covered.  What will happen when a new prefix is added?

**Comment by vbchrisrj** [comment]
I have a few from my logs that aren't in your list.  These have been logged by my BBS (cjsplace.thruhere.net).

[Stretchoid Hosts.txt](https://github.com/user-attachments/files/16516758/Stretchoid.Hosts.txt)

**Comment by Xorlent** [comment]
> I have a few from my logs that aren't in your list. These have been logged by my BBS (cjsplace.thruhere.net).
> 
> [Stretchoid Hosts.txt](https://github.com/user-attachments/files/16516758/Stretchoid.Hosts.txt)

Thank you.  I assume you compared to the version of the list that was checked in about 20 minutes prior to this post?  The initial list generation just completed.  I will review your data!

**Comment by Xorlent** [comment]
I believe the list is now complete, please let me know if you find anything else missing.  Again, thanks for your contributions!
